---
# Source: mimir-distributed/templates/nginx/nginx-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: krajo-mimir-nginx
  labels:
    helm.sh/chart: mimir-distributed-3.1.0-weekly.202
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: krajo
    app.kubernetes.io/component: nginx
    app.kubernetes.io/version: "r202"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
  namespace: "default"
spec:
  type: ClusterIP
  ports:
    - name: http-metric
      port: 80
      targetPort: http-metric
      protocol: TCP
  selector:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: krajo
    app.kubernetes.io/component: nginx
