---
# Source: mimir-distributed/charts/minio/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: krajo-minio
  namespace: "default"
  labels:
    app: minio
    release: krajo
    heritage: Helm
    monitoring: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
    release: krajo
