---
# Source: mimir-distributed/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: krajo-mimir
  labels:
    helm.sh/chart: mimir-distributed-3.1.0-weekly.202
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: krajo
    app.kubernetes.io/version: "r202"
    app.kubernetes.io/managed-by: Helm
  namespace: "default"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: krajo-mimir
subjects:
- kind: ServiceAccount
  name: krajo-mimir
