rollout_operator:
  enabled: true

store_gateway:
  zoneAwareReplication:
    enabled: true
    zones:
    - name: zone-a
      nodeSelector:
        topology.kubernetes.io/zone: zone-a
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: rollout-group
                    operator: In
                    values:
                      - store-gateway
                  - key: app.kubernetes.io/component
                    operator: NotIn
                    values:
                      - store-gateway-zone-a
              topologyKey: 'kubernetes.io/hostname'
    - name: zone-b
      nodeSelector:
        topology.kubernetes.io/zone: zone-b
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: rollout-group
                    operator: In
                    values:
                      - store-gateway
                  - key: app.kubernetes.io/component
                    operator: NotIn
                    values:
                      - store-gateway-zone-b
              topologyKey: 'kubernetes.io/hostname'
    - name: zone-c
      nodeSelector:
        topology.kubernetes.io/zone: zone-c
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: rollout-group
                    operator: In
                    values:
                      - store-gateway
                  - key: app.kubernetes.io/component
                    operator: NotIn
                    values:
                      - store-gateway-zone-c
              topologyKey: 'kubernetes.io/hostname'

ingester:
  zoneAwareReplication:
    enabled: true
    zones:
    - name: zone-a
      nodeSelector:
        topology.kubernetes.io/zone: zone-a
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: rollout-group
                    operator: In
                    values:
                      - store-gateway
                  - key: app.kubernetes.io/component
                    operator: NotIn
                    values:
                      - store-gateway-zone-a
              topologyKey: 'kubernetes.io/hostname'
    - name: zone-b
      nodeSelector:
        topology.kubernetes.io/zone: zone-b
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: rollout-group
                    operator: In
                    values:
                      - store-gateway
                  - key: app.kubernetes.io/component
                    operator: NotIn
                    values:
                      - store-gateway-zone-b
              topologyKey: 'kubernetes.io/hostname'
    - name: zone-c
      nodeSelector:
        topology.kubernetes.io/zone: zone-c
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: rollout-group
                    operator: In
                    values:
                      - store-gateway
                  - key: app.kubernetes.io/component
                    operator: NotIn
                    values:
                      - store-gateway-zone-c
              topologyKey: 'kubernetes.io/hostname'

alertmanager:
  zoneAwareReplication:
    enabled: true
    zones:
    - name: zone-a
      nodeSelector:
        topology.kubernetes.io/zone: zone-a
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: rollout-group
                    operator: In
                    values:
                      - store-gateway
                  - key: app.kubernetes.io/component
                    operator: NotIn
                    values:
                      - store-gateway-zone-a
              topologyKey: 'kubernetes.io/hostname'
    - name: zone-b
      nodeSelector:
        topology.kubernetes.io/zone: zone-b
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: rollout-group
                    operator: In
                    values:
                      - store-gateway
                  - key: app.kubernetes.io/component
                    operator: NotIn
                    values:
                      - store-gateway-zone-b
              topologyKey: 'kubernetes.io/hostname'
    - name: zone-c
      nodeSelector:
        topology.kubernetes.io/zone: zone-c
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: rollout-group
                    operator: In
                    values:
                      - store-gateway
                  - key: app.kubernetes.io/component
                    operator: NotIn
                    values:
                      - store-gateway-zone-c
              topologyKey: 'kubernetes.io/hostname'
