rollout_operator:
  enabled: true

store_gateway:
  zoneAwareReplication:
    enabled: true
    topologyKey: 'kubernetes.io/hostname'
    zones:
    - name: zone-a
      nodeSelector:
        topology.kubernetes.io/zone: zone-a
    - name: zone-b
      nodeSelector:
        topology.kubernetes.io/zone: zone-b
    - name: zone-c
      nodeSelector:
        topology.kubernetes.io/zone: zone-c

ingester:
  zoneAwareReplication:
    enabled: true
    topologyKey: 'kubernetes.io/hostname'
    zones:
    - name: zone-a
      nodeSelector:
        topology.kubernetes.io/zone: zone-a
    - name: zone-b
      nodeSelector:
        topology.kubernetes.io/zone: zone-b
    - name: zone-c
      nodeSelector:
        topology.kubernetes.io/zone: zone-c

alertmanager:
  zoneAwareReplication:
    enabled: true
    topologyKey: 'kubernetes.io/hostname'
    zones:
    - name: zone-a
      nodeSelector:
        topology.kubernetes.io/zone: zone-a
    - name: zone-b
      nodeSelector:
        topology.kubernetes.io/zone: zone-b
    - name: zone-c
      nodeSelector:
        topology.kubernetes.io/zone: zone-c
