---
# Source: mimir-distributed/templates/store-gateway/store-gateway-pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: krajo-mimir-store-gateway
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: krajo
    app.kubernetes.io/component: store-gateway
    app.kubernetes.io/managed-by: Helm
  namespace: "default"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
      app.kubernetes.io/instance: krajo
      app.kubernetes.io/component: store-gateway
  maxUnavailable: 1
