---
# Source: mimir-distributed/charts/minio/templates/console-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: krajo-minio-console
  namespace: "default"
  labels:
    app: minio
    chart: minio-4.0.12
    release: krajo
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: minio
    release: krajo
