---
# Source: mimir-distributed/charts/minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: krajo-minio
  namespace: "default"
  labels:
    app: minio
    release: krajo
    heritage: Helm
type: Opaque
data:
  rootUser: "Z3JhZmFuYS1taW1pcg=="
  rootPassword: "c3VwZXJzZWNyZXQ="
