---
# Source: mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: krajo-rollout-operator
  labels:
    app.kubernetes.io/name: rollout-operator
    app.kubernetes.io/instance: krajo
    app.kubernetes.io/managed-by: Helm
