---
# Source: mimir-distributed/templates/runtime-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: krajo-mimir-runtime
  labels:
    helm.sh/chart: mimir-distributed-3.1.0-weekly.202
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: krajo
    app.kubernetes.io/version: "r202"
    app.kubernetes.io/managed-by: Helm
  namespace: "default"
data:
  runtime.yaml: |
    
    {}
