# Test values to limit the load during CI
kubeVersionOverride: "1.20"

# Remove resource requests and limits because in CI we only have limited memory and CPU
ci_resources: &ci_resources
  requests:
  limits:

alertmanager:
  resources:
    <<: *ci_resources
  persistentVolume:
    enabled: false
  zoneAwareReplication:
    enabled: true
    topologyKey: 'kubernetes.io/hostname'

compactor:
  resources:
    <<: *ci_resources
  persistentVolume:
    enabled: false

ingester:
  resources:
    <<: *ci_resources
  persistentVolume:
    enabled: false
  zoneAwareReplication:
    enabled: true
    topologyKey: 'kubernetes.io/hostname'
    zones:
    - name: zone-a
      extraAffinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: security
                operator: In
                values:
                - S1
            topologyKey: topology.kubernetes.io/zone
    - name: zone-b
      extraAffinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: security
                operator: In
                values:
                - S1
            topologyKey: topology.kubernetes.io/zone
    - name: zone-c
      extraAffinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: security
                operator: In
                values:
                - S1
            topologyKey: topology.kubernetes.io/zone

store_gateway:
  resources:
    <<: *ci_resources
  persistentVolume:
    enabled: false
  zoneAwareReplication:
    enabled: true
    topologyKey: 'kubernetes.io/hostname'
    zones:
    - name: zone-a
      nodeSelector:
        topology.kubernetes.io/zone: zone-a
    - name: zone-b
      nodeSelector:
        topology.kubernetes.io/zone: zone-b
    - name: zone-c
      nodeSelector:
        topology.kubernetes.io/zone: zone-c

querier:
  resources:
    <<: *ci_resources

query_frontend:
  resources:
    <<: *ci_resources

query_scheduler:
  resources:
    <<: *ci_resources
