---
# Source: mimir-distributed/templates/smoke-test/smoke-test-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: krajo-mimir-smoke-test
  labels:
    helm.sh/chart: mimir-distributed-3.1.0-weekly.202
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: krajo
    app.kubernetes.io/component: smoke-test
    app.kubernetes.io/version: "r202"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
  namespace: "default"
spec:
  backoffLimit: 5
  completions: 1
  parallelism: 1
  selector:
  template:
    metadata:
      labels:
        helm.sh/chart: mimir-distributed-3.1.0-weekly.202
        app.kubernetes.io/name: mimir
        app.kubernetes.io/instance: krajo
        app.kubernetes.io/version: "r202"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: smoke-test
    spec:
      serviceAccountName: krajo-mimir
      securityContext:
        null
      initContainers:
        []
      containers:
        - name: smoke-test
          image: "grafana/mimir-continuous-test:r202-d1db3dc"
          imagePullPolicy: 
          args:
            - "-tests.smoke-test"
            - "-tests.write-endpoint=http://krajo-mimir-nginx.default.svc:80"
            - "-tests.read-endpoint=http://krajo-mimir-nginx.default.svc:80/prometheus"
            - "-tests.tenant-id="
            - "-tests.write-read-series-test.num-series=1000"
            - "-tests.write-read-series-test.max-query-age=48h"
            - "-server.metrics-port=8080"
          volumeMounts:
          env:
          envFrom:
      restartPolicy: OnFailure
      volumes:
